apps/urls.py
from django.urls import path

from . import views

app_name = 'apps'
urlpatterns = [

    # Authentication Routes
    path('', views.Index.as_view(), name='index'),
    path('register/', views.Register.as_view(), name='reg'),
    path('login/', views.Login_View.as_view(), name='login'),
    path('logout/', views.Logout_View.as_view(), name='logout'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),

    # Employee Routes
    path('dashboard/employee/', views.Employee_All.as_view(), name='employee_all'),
    path('dashboard/employee/new/', views.Employee_New.as_view(), name='employee_new'),
    path('dashboard/employee/<int:pk>/view/', views.Employee_View.as_view(), name='employee_view'),
    path('dashboard/employee/<int:pk>/update/', views.Employee_Update.as_view(), name='employee_update'),
    path('dashboard/employee/<int:pk>/delete/', views.delete_employee, name='employee_delete'),
    path('dashboard/employee/<int:id>/kin/add/', views.Employee_Kin_Add.as_view(), name='kin_add'),
    path('dashboard/employee/<int:id>/kin/<int:pk>/update/', views.Employee_Kin_Update.as_view(), name='kin_update'),

    # Department Routes
    path('dashboard/department/<int:pk>/', views.Department_Detail.as_view(), name='dept_detail'),
    path('dashboard/department/add/', views.Department_New.as_view(), name='dept_new'),
    path('dashboard/department/<int:pk>/update/', views.Department_Update.as_view(), name='dept_update'),

    # Attendance Routes
    path('dashboard/attendance/in/', views.Attendance_New.as_view(), name='attendance_new'),
    path('dashboard/attendance/<int:pk>/out/', views.Attendance_Out.as_view(), name='attendance_out'),

    # Leave Routes

    path("dashboard/leave/new/", views.LeaveNew.as_view(), name="leave_new"),

    # Recruitment

    path("recruitment/", views.RecruitmentNew.as_view(), name="recruitment"),
    path("recruitment/all/", views.RecruitmentAll.as_view(), name="recruitmentall"),
    path("recruitment/<int:pk>/delete/", views.RecruitmentDelete.as_view(), name="recruitmentdelete"),

    # Payroll
    path("employee/pay/", views.Pay.as_view(), name="payroll")

]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static  # this is needed for file and image upload
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls', namespace='apps')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/templates/hrms/employee/create.html
{% extends 'hrms/layout.html' %}
{% load static %}
{% block title %} Новый сотрудник | HRIS {% endblock title %}

{% block content %}

    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-lg-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                           <h4 class="text-center text-primary"><i class="fa fa-plus">&emsp; Новый сотрудник </i></h4><hr>
                                <form enctype="multipart/form-data" action="{% url 'apps:employee_new' %}" class="form-group" method="POST">
                                    {% csrf_token %}
                                    <small class="mb-5">** Все поля обязательны к заполнению</small>
                                        {{form.as_p}}
                                    <div class="text-center mt-3">
                                        <button class="btn btn-outline-success"><i class="mdi mdi-file-document"></i>Добавить сотрудника</button></button>
                                        
                                    </div>
                                </form>
                        
                                           
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

apps/templates/hrms/employee/edit.html
{% extends 'hrms/layout.html' %}
{% load static %}
{% block title %} Изменить сотрудника | HRIS {% endblock title %}

{% block content %}

    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'apps:dashboard' %}">Панель приборов</a></li>
                        <li class="breadcrumb-item active" aria-current="page"><a
                                href=" {% url 'apps:employee_all' %} ">Работник</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Редактировать</li>
                    </ol>
                </nav>
                <div class="col-lg-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="text-center text-primary"><i class="fa fa-edit">&emsp; Изменить сотрудника </i>
                            </h4>
                            <hr>
                            <form enctype="multipart/form-data" class="form-group" method="POST">
                                {% csrf_token %}
                                <small class="mb-5">** Все поля обязательны к заполнению</small>
                                {{ form.as_p }}
                                <div class="text-center mt-3">
                                    <button class="btn btn-outline-success btn-rounded"><i
                                            class="mdi mdi-cloud-download"></i>Обновить сотрудника
                                    </button>
                                    </button>

                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

{% endblock content %}

apps/templates/hrms/employee/index.html
{% extends 'hrms/layout.html' %}
{% load static %}
{% block title %} Все работники | HRIS {% endblock title %}
      <!--  MAIN BODY START HERE -->
          {% block content %}

      <div class="main-panel">
        <div class="content-wrapper">
          <div class="row">
            <div class="row">
            <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'apps:dashboard' %}">Панель приборов</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Работник </li>
                        <li class="breadcrumb-item active" aria-current="page">Все</li>
                    </ol>
                </nav>
            <form method='GET'>
              <input type='text' name='q' value='{{ request.GET.q }}'>
              <input class="button" type='submit' value="Search Profile">
            </form>
            <div class="col-lg-12 grid-margin">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Все работники<a href="{% url 'apps:employee_new' %}" class="btn btn-sm btn-success mb-3 float-right">Добавить новое +</a></h4>
                    
                  <div class="table-responsive">
                    <table class="table table-bordered">
                      <thead>
                        <tr>
                          <th>
                            Миниатюра
                          </th>
                          <th>
                            Имя
                          </th>
                          <th>
                            Фамилия
                          </th>
                          <th>
                            телефон
                          </th>
                          <th>
                            Электронная почта
                          </th> 
                          <th>
                            Действия
                          </th>                         
                        </tr>
                      </thead>
                      <tbody>
                      {% for employee in employees  %}
                        <tr>
                          <td class="font-weight-medium">
                            <img src="{{employee.thumb.url}}" class='rounded img-fluid' alt="">
                          </td>
                          <td>
                            {{employee.first_name}}
                          </td>
                          <td>
                            {{employee.last_name}}
                          </td>
                          <td>
                           {{employee.mobile}}
                          </td>
                          <td class="text-danger"> 
                            {{employee.email}}
                          </td>
                          <td>
                          
                            <div class="btn-group dropdown">
                              <button type="button" class="btn btn-success dropdown-toggle btn-rounded btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                               <i class="fa fa-cog "></i> Управлять
                              </button>
                              <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'apps:employee_view' pk=employee.pk %}">
                                  <i class="fa fa-eye text-success fa-fw"></i>Посмотреть</a>
                                <a class="dropdown-item" href="{% url 'apps:employee_update' pk=employee.pk %}">
                                  <i class="fa fa-edit text-info fa-fw"></i>Редактировать</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'apps:employee_delete' pk=employee.pk %}">
                                  <i class="fa fa-trash text-danger fa-fw"></i>Удалить</a>
                              </div>
                            </div>                  
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>

                    {% if is_paginated %}
                      <nav aria-label="Page navigation example" class='mt-4'>
                        <ul class="pagination">
                        {% if page_obj.has_previous %}
                          <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Предыдущий</a></li>
                        {% else %}

                          <li class="page-item disabled"><span class='page-link '>Предыдущий</span></li>
                        {% endif %}
                          <li class="disabled"> <span class='page-link'> Page {{page_obj.number}} of {{page_obj.paginator.num_pages}} </span></li>
                        {% if page_obj.has_next %}
                          <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Следующий</a></li>
                        {% else %}
                          <li class="page-item disabled"><span class='page-link '>Следующий</span></li>
                        {% endif %}                        
                        </ul>
                    </nav>
                    {% endif %}
                
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
        {% block noty %}
        <script>
          {% if messages %}
            {% for message in messages  %}
              toastr.success('{{message}}')
            {% endfor %}
          {% endif %}
        </script>
        {% endblock noty %}
        {% endblock content %}

apps/templates/hrms/employee/kin_add.html
{% extends 'hrms/layout.html' %}
{% load static %}
{% block title %} Близкий родственник | HRIS {% endblock title %}

{% block content %}

    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-lg-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="text-center text-primary"><i class="fa fa-plus">&emsp; Информация о близкий
                                родственниках. </i>
                            </h4>
                            <hr>
                            <div class="alert alert-warning" role="alert">
                                <p class="lead">Примечание. Отображаются только сотрудники, не имеющие ближайших
                                    родственников.</p>
                                <p class="lead text-center">Пожалуйста, выберите: <strong>
                                    '{{ emp.first_name |upper }}'</strong> в ящике сотрудника</p>
                            </div>
                            <form class="form-group" method="POST">
                                {% csrf_token %}
                                <small class="mb-5">** Все поля обязательны к заполнению</small>
                                {{ form.as_p }}
                                <div class="text-center mt-3">
                                    <button class="btn btn-outline-success"><i class="mdi mdi-file-document"></i>Обновлять
                                    </button>
                                    </button>

                                </div>
                            </form>


                        </div>
                    </div>
                </div>
            </div>

{% endblock content %}

apps/templates/hrms/employee/kin_update.html
{% extends 'hrms/layout.html' %}
{% load static %}
{% block title %} Edit Next of Kin| HRIS {% endblock title %}

{% block content %}

    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-lg-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                           <h4 class="text-center text-primary"><i class="fa fa-edit">&emsp; Edit Next of Kin </i></h4><hr>
                                <form class="form-group" method="POST">
                                    {% csrf_token %}
                                    <small class="mb-5">** All Fields are required</small><br>
                                        {{form.as_p}}
                                        {% comment %} {{form.first_name.label }}
                                        {{form.first_name}}
                                        
                                        {{form.last_name.label }}
                                        {{form.last_name}}

                                        {{form.address.label }}
                                        {{form.address}}

                                        {{form.occupation.label }}
                                        {{form.occupation}}

                                        {{form.mobile.label }}
                                        {{form.mobile}} {% endcomment %}
                                    <div class="text-center mt-3">
                                        <button class="btn btn-outline-success btn-rounded"><i class="mdi mdi-cloud-download"></i>Update Employee</button></button>   
                                    </div>
                                </form>                   
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

apps/templates/hrms/employee/single.html
{% extends 'hrms/layout.html' %}
{% load static %}
{% block title %} Информация о сотруднике | HRIS {% endblock title %}
{% block content %}

    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-lg-12 grid-margin">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'apps:dashboard' %}">Панель приборов</a></li>
                            <li class="breadcrumb-item active" aria-current="page"><a
                                    href=" {% url 'apps:employee_all' %} ">Работник</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Посмотреть</li>
                        </ol>
                    </nav>
                    <div class="card">
                        <div class="card-body">
                            <h4 class="text-center text-primary"><i class="fa fa-address-book-o">&emsp; Сотрудники
                                Профиль</i></h4>
                            <hr>
                            <div class="row">
                                <div class="col-lg-2 col-md-2 d-flex align-items-stretch grid-margin">

                                    <div class="card border-top border-bottom border-success">
                                        <div class="card-body">
                                            <img src="{{ employee.thumb.url }}" alt="" class="img-fluid" width='200px'
                                                 height='200px'>
                                            <p class="lead mt-2 text-center">
                                                {{ employee.emp_id | capfirst }} <br>
                                                <small class='text-center text-secondary'>( ID )</small>
                                            </p>

                                        </div>
                                    </div>


                                </div>
                                <!-- Second column -->
                                <div class="col-lg-6 col-md-6">
                                    <div class="table-responsive border-top border-success table-striped">
                                        <p class="lead text-center mt-2">Личная информация.</p>
                                        <table class="table">
                                            <tr>
                                                <th style="width:50%">Имя:</th>
                                                <td>{{ employee.first_name }}</td>
                                            </tr>
                                            <tr>
                                                <th>Фамилия</th>
                                                <td>{{ employee.last_name }}</td>
                                            </tr>
                                            <tr>
                                                <th>Мобильный:</th>
                                                <td>{{ employee.mobile }}</td>
                                            </tr>
                                            <tr>
                                                <th>Эл. адрес:</th>
                                                <td>{{ employee.email }}</td>
                                            </tr>
                                            <tr>
                                                <th>Пол:</th>
                                                <td>{{ employee.gender }}</td>
                                            </tr>
                                            <tr>
                                                <th>Отделение:</th>
                                                <td>{{ employee.department }}</td>
                                            </tr>
                                            <tr>
                                                <th>Язык:</th>
                                                <td>{{ employee.language | capfirst }}</td>
                                            </tr>
                                            <tr>
                                                <th>Месячная зарплата:</th>
                                                <td>#{{ employee.salary }}</td>
                                            </tr>
                                            <tr>
                                                <th>Дата поступления на работу:</th>
                                                <td>{{ employee.joined }} </td>
                                            </tr>
                                            <tr>
                                                <th>ИНН:</th>
                                                <td>{{ employee.nuban }} </td>
                                            </tr>
                                            <tr>
                                                <th>Банк:</th>
                                                <td>{{ employee.bank }} </td>

                                            </tr>

                                        </table>
                                        <div class="text-center mt-3">
                                            <a href=" {% url 'apps:employee_update' pk=employee.id %}"
                                               class="btn btn-lg btn-warning">Обновлять</a>
                                        </div>
                                    </div>
                                </div>
                                <!-- Third column-->

                                <div class="col-lg-4 col-md-4">
                                    <div class="table-responsive border-top border-success  table-striped">
                                        <p class="lead text-center mt-2">Близкий родственник</p>
                                        <table class="table">
                                            {% if kin %}
                                                <tr>
                                                    <th style="width:50%">Имя:</th>
                                                    <td>{{ kin.first_name }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Фамилия</th>
                                                    <td>{{ kin.last_name }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Мобильный:</th>
                                                    <td>{{ kin.mobile }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Адрес:</th>
                                                    <td>{{ kin.address }} </td>
                                                </tr>
                                                <tr>
                                                    <th>Занятие:</th>
                                                    <td>{{ kin.occupation | capfirst }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Относительный:</th>
                                                    <td>{{ kin.employee.first_name }}
                                                        - {{ kin.employee.last_name }} </td>
                                                </tr>

                                                <tr>
                                                    <td><a href="{% url 'apps:kin_update' pk=kin.pk id=employee.id %}"
                                                           class=" btn btn-warning"> Обновить близкий родственник</a>
                                                    </td>
                                                </tr>
                                            {% else %}
                                                <p class="lead text-center">
                                                    OOPs! <br> Информация о близкий родственник не указана.
                                                </p>

                                                <div class="text-center">
                                                    <a href="{% url 'apps:kin_add' id=employee.id %}"
                                                       class='btn btn-danger btn-rounded'> <i
                                                            class="mdi mdi-upload"></i> Загрузить сейчас </a>
                                                </div>

                                            {% endif %}
                                        </table>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

{% endblock content %}