apps/urls.py
from django.urls import path

from . import views

app_name = 'apps'
urlpatterns = [

    # Authentication Routes
    path('', views.Index.as_view(), name='index'),
    path('register/', views.Register.as_view(), name='reg'),
    path('login/', views.Login_View.as_view(), name='login'),
    path('logout/', views.Logout_View.as_view(), name='logout'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),

    # Employee Routes
    path('dashboard/employee/', views.Employee_All.as_view(), name='employee_all'),
    path('dashboard/employee/new/', views.Employee_New.as_view(), name='employee_new'),
    path('dashboard/employee/<int:pk>/view/', views.Employee_View.as_view(), name='employee_view'),
    path('dashboard/employee/<int:pk>/update/', views.Employee_Update.as_view(), name='employee_update'),
    path('dashboard/employee/<int:pk>/delete/', views.delete_employee, name='employee_delete'),
    path('dashboard/employee/<int:id>/kin/add/', views.Employee_Kin_Add.as_view(), name='kin_add'),
    path('dashboard/employee/<int:id>/kin/<int:pk>/update/', views.Employee_Kin_Update.as_view(), name='kin_update'),

    # Department Routes
    path('dashboard/department/<int:pk>/', views.Department_Detail.as_view(), name='dept_detail'),
    path('dashboard/department/add/', views.Department_New.as_view(), name='dept_new'),
    path('dashboard/department/<int:pk>/update/', views.Department_Update.as_view(), name='dept_update'),

    # Attendance Routes
    path('dashboard/attendance/in/', views.Attendance_New.as_view(), name='attendance_new'),
    path('dashboard/attendance/<int:pk>/out/', views.Attendance_Out.as_view(), name='attendance_out'),

    # Leave Routes

    path("dashboard/leave/new/", views.LeaveNew.as_view(), name="leave_new"),

    # Recruitment

    path("recruitment/", views.RecruitmentNew.as_view(), name="recruitment"),
    path("recruitment/all/", views.RecruitmentAll.as_view(), name="recruitmentall"),
    path("recruitment/<int:pk>/delete/", views.RecruitmentDelete.as_view(), name="recruitmentdelete"),

    # Payroll
    path("employee/pay/", views.Pay.as_view(), name="payroll")

]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static  # this is needed for file and image upload
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls', namespace='apps')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/templates/hrms/attendance/create.html
{% extends 'hrms/layout.html' %}
{% load static %}
{% block title %} Посещаемость| HRIS {% endblock title %}

{% block content %}

    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'apps:dashboard' %}">Панель приборов</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Посещаемость</li>
                    </ol>
                </nav>
                <div class="col-lg-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="text-center text-primary"><i class="fa  fa-check-square-o">&emsp; Работник
                                Посещаемость </i></h4>
                            <hr>
                            <form class="form-group" method="POST">
                                {% csrf_token %}
                                <small class="mb-5">** Все поля обязательны к заполнению</small><br>
                                {{ form.errors }}
                                <div class="table-responsive">
                                    <table class="table table-striped">
                                        <thead>
                                        <tr>
                                            <th>
                                                Дата
                                            </th>

                                            <th>
                                                Штатный сотрудник
                                            </th>
                                            <th>
                                                Статус
                                            </th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td class="py-1">
                                                {{ today }}
                                            </td>

                                            <td>
                                                {{ form.staff }}
                                            </td>
                                            <td>
                                                {{ form.status }}
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>


                                <div class="text-center mt-3">
                                    <button class="btn btn-rounded btn-outline-success"><i class="mdi mdi-check"></i>Знак
                                        в
                                    </button>
                                    </button>
                                </div>
                            </form>
                            <br>
                            <h4 class="text-center text-primary"><i class="fa  fa-sign-in">&emsp; Вошел
                                Штатный сотрудник (ы) </i></h4>
                            <hr>
                            {% if present_staffers %}
                                <small class='text-center'>Это список сотрудников, которые в настоящее время
                                    настоящее время. </small>
                                <div class="table-responsive">
                                    <table class="table table-striped">
                                        <thead>
                                        <tr>
                                            <th>
                                                Дата
                                            </th>
                                            <th>
                                                Первый в (прибытие)
                                            </th>
                                            <th>
                                                Последний выход (отъезд)
                                            </th>
                                            <th>
                                                Имя
                                            </th>
                                            <th>
                                                Действие(я)
                                            </th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for ps in present_staffers %}
                                            <tr>
                                                <td class="py-1">
                                                    {{ today }}
                                                </td>
                                                <td>
                                                    <strong>{{ ps.first_in }}</strong>
                                                </td>
                                                <td>

                                                    <strong>{{ ps.last_out }}</strong>
                                                </td>
                                                <td>
                                                    {{ ps.staff.first_name }} - {{ ps.staff.last_name }}
                                                </td>
                                                <td>
                                                    <a href="{% url 'apps:attendance_out' pk=ps.staff.pk %}"
                                                            {% if not ps.last_out %}
                                                       class="btn btn-sm btn-info"  {% endif %}
                                                       class="btn btn-sm btn-info disabled"> <i
                                                            class="fa fa-sign-out"></i> Выход</a>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            {% else %}
                                <p class="lead"> В настоящее время в системе нет сотрудников</p>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>

{% endblock content %}

apps/templates/hrms/attendance/edit.html
{% extends 'hrms/layout.html' %}
{% load static %}
{% block title %} Edit Employee | HRIS {% endblock title %}

{% block content %}

    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-lg-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                           <h4 class="text-center text-primary"><i class="fa fa-edit">&emsp; Edit Department </i></h4><hr>
                                <form  class="form-group" method="POST">
                                    {% csrf_token %}
                                    <small class="mb-5">** All Fields are required</small>
                                        {{form.as_p}}
                                    <div class="text-center mt-3">
                                        <button class="btn btn-outline-success btn-rounded"><i class="mdi mdi-cloud-download"></i>Update Department</button></button>
                                        
                                    </div>
                                </form>                   
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

apps/templates/hrms/attendance/single.html
{% extends 'hrms/layout.html' %}
{% load static %}
{% block title %} Department Info | HRIS {% endblock title %}
{% block content %}

    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-lg-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                            <span class="lead">{{dept.name | capfirst}} Department <a href="{% url 'apps:dept_update' dept.pk %}" class="btn btn-rounded btn-success float-right"> <i class="fa fa-edit"></i>  Update Info</a></span><hr>
                                <div class="row">
                                <!--First Column-->
                                    <div class="col-lg-5">
                                        <div class="card border-left border-info shadow-sm">
                                            <div class="card-body">
                                                <p class="lead">Brief History</p>
                                                <p class='text-justify'>
                                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus, inventore assumenda fugiat repudiandae delectus id libero dolor veritatis natus architecto?
                                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus, inventore assumenda fugiat repudiandae delectus id libero dolor veritatis natus architecto?
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                       <!--Second Column-->
                                    <div class="col-lg-7">
                                        <div class="card border-right border-info shadow-sm">
                                            <div class="card-body">
                                                <p class="lead">Associated Employees</p>
                                                <div class="row">
                                                {% if employees %}
                                                    {% for employee in employees  %}
                                                        <div class="col-lg">
                                                            <div class="card border-bottom border-top border-info">
                                                                <div class="card-body">
                                                                    <div class='text-center'>
                                                                        <img class='img-fluid' src="{{employee.thumb.url}}" width='100' height='100' alt="{{employee.first_name}}">
                                                                        <p>{{employee.last_name|capfirst}}.{{employee.first_name|slice:1}}</p>
                                                                        <p>({{employee.emp_id|capfirst}})</p>
                                                                        <div>
                                                                            <a href="{% url 'apps:employee_view' pk=employee.pk %}" class=" badge badge-info">view profile</a>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    {% endfor %}
                                                {% else %}
                                                    <p class="lead text-center"> No Associated Employee</p>
                                                {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                
                                       
                                
                    </div>                     
                                        
                </div>
            </div>
        </div>
    </div>

{% endblock content %}