apps/urls.py
from django.urls import path

from . import views

app_name = 'apps'
urlpatterns = [

    # Authentication Routes
    path('', views.Index.as_view(), name='index'),
    path('register/', views.Register.as_view(), name='reg'),
    path('login/', views.Login_View.as_view(), name='login'),
    path('logout/', views.Logout_View.as_view(), name='logout'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),

    # Employee Routes
    path('dashboard/employee/', views.Employee_All.as_view(), name='employee_all'),
    path('dashboard/employee/new/', views.Employee_New.as_view(), name='employee_new'),
    path('dashboard/employee/<int:pk>/view/', views.Employee_View.as_view(), name='employee_view'),
    path('dashboard/employee/<int:pk>/update/', views.Employee_Update.as_view(), name='employee_update'),
    path('dashboard/employee/<int:pk>/delete/', views.delete_employee, name='employee_delete'),
    path('dashboard/employee/<int:id>/kin/add/', views.Employee_Kin_Add.as_view(), name='kin_add'),
    path('dashboard/employee/<int:id>/kin/<int:pk>/update/', views.Employee_Kin_Update.as_view(), name='kin_update'),

    # Department Routes
    path('dashboard/department/<int:pk>/', views.Department_Detail.as_view(), name='dept_detail'),
    path('dashboard/department/add/', views.Department_New.as_view(), name='dept_new'),
    path('dashboard/department/<int:pk>/update/', views.Department_Update.as_view(), name='dept_update'),

    # Attendance Routes
    path('dashboard/attendance/in/', views.Attendance_New.as_view(), name='attendance_new'),
    path('dashboard/attendance/<int:pk>/out/', views.Attendance_Out.as_view(), name='attendance_out'),

    # Leave Routes

    path("dashboard/leave/new/", views.LeaveNew.as_view(), name="leave_new"),

    # Recruitment

    path("recruitment/", views.RecruitmentNew.as_view(), name="recruitment"),
    path("recruitment/all/", views.RecruitmentAll.as_view(), name="recruitmentall"),
    path("recruitment/<int:pk>/delete/", views.RecruitmentDelete.as_view(), name="recruitmentdelete"),

    # Payroll
    path("employee/pay/", views.Pay.as_view(), name="payroll")

]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static  # this is needed for file and image upload
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls', namespace='apps')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/templates/hrms/home/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href=" {% static 'hrms/css/style.css' %} ">
    <style>
        /*
        .body-bg{
           background: #108dc7;
            background: -webkit-linear-gradient(to right, #ef8e38, #108dc7);
            background: linear-gradient(to right, #ef8e38, #108dc7);
        }
        */
        .btn-orange {
            background: #FDC830; /* fallback for old browsers */
            background: -webkit-linear-gradient(to right, #F37335, #FDC830); /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to right, #F37335, #FDC830); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        }

        .btn-selenium {
            background: #0f0c29; /* fallback for old browsers */
            background: -webkit-linear-gradient(to right, #24243e, #302b63, #0f0c29); /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to right, #24243e, #302b63, #0f0c29); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

        }
    </style>
    <title>Главная</title>
</head>
<body class='body-bg'>
<section class="container">
    <nav class="navbar navbar-light bg-light mt-3 mb-2 ">
        <h1 class="display-4 mt-2 text-right text-warning"><a href=" {% url 'apps:recruitment' %} "
                                                              class="btn  btn-selenium text-light"> Мы нанимаем !!! </a>
            &emsp; &emsp; &emsp; &emsp; Проект по информационной системе управления персоналом</h1>
    </nav>

    <div class="row">
        <div class="col-lg-6">
            <img src="{% static 'hrms/images/hr.png' %}" class='img-fluid' alt="">
        </div>
        <div class="col-lg-6">
            <div class="card mb-3 shadow">
                <div class="card-header btn-orange pt-4">
                    <p class="lead">Введение и понимание</p>
                </div>

                <div class="card-body">
                    <p class="lead text-justify">
                        Информационная система управления персоналом (HRIS) — это программное обеспечение или
                        онлайн-решение для сбора данных.
                        ввод, отслеживание данных и информационные потребности в данных отдела кадров, начисления
                        заработной платы,
                        управленческие и бухгалтерские функции в бизнесе.
                        Проще говоря, информационная система управления персоналом — это система, позволяющая
                        отслеживать
                        всех ваших сотрудников и информацию о них. Обычно это делается в базе данных или, что чаще, в
                        ряде взаимосвязанных баз данных.
                    </p>
                    <a href=" {% url 'apps:login' %} " class="btn btn-block btn-selenium text-light"> Администратор
                        &rarr; </a>
                </div>
            </div>
        </div>
    </div>
</section>

<nav class="navbar navbar-light bg-light ">
    <p class="display-4 mx-auto bg-light">Разработан Бахромов Шахзодбек</p>
</nav>
</body>
</html>