apps/urls.py
from django.urls import path

from . import views

app_name = 'apps'
urlpatterns = [

    # Authentication Routes
    path('', views.Index.as_view(), name='index'),
    path('register/', views.Register.as_view(), name='reg'),
    path('login/', views.Login_View.as_view(), name='login'),
    path('logout/', views.Logout_View.as_view(), name='logout'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),

    # Employee Routes
    path('dashboard/employee/', views.Employee_All.as_view(), name='employee_all'),
    path('dashboard/employee/new/', views.Employee_New.as_view(), name='employee_new'),
    path('dashboard/employee/<int:pk>/view/', views.Employee_View.as_view(), name='employee_view'),
    path('dashboard/employee/<int:pk>/update/', views.Employee_Update.as_view(), name='employee_update'),
    path('dashboard/employee/<int:pk>/delete/', views.delete_employee, name='employee_delete'),
    path('dashboard/employee/<int:id>/kin/add/', views.Employee_Kin_Add.as_view(), name='kin_add'),
    path('dashboard/employee/<int:id>/kin/<int:pk>/update/', views.Employee_Kin_Update.as_view(), name='kin_update'),

    # Department Routes
    path('dashboard/department/<int:pk>/', views.Department_Detail.as_view(), name='dept_detail'),
    path('dashboard/department/add/', views.Department_New.as_view(), name='dept_new'),
    path('dashboard/department/<int:pk>/update/', views.Department_Update.as_view(), name='dept_update'),

    # Attendance Routes
    path('dashboard/attendance/in/', views.Attendance_New.as_view(), name='attendance_new'),
    path('dashboard/attendance/<int:pk>/out/', views.Attendance_Out.as_view(), name='attendance_out'),

    # Leave Routes

    path("dashboard/leave/new/", views.LeaveNew.as_view(), name="leave_new"),

    # Recruitment

    path("recruitment/", views.RecruitmentNew.as_view(), name="recruitment"),
    path("recruitment/all/", views.RecruitmentAll.as_view(), name="recruitmentall"),
    path("recruitment/<int:pk>/delete/", views.RecruitmentDelete.as_view(), name="recruitmentdelete"),

    # Payroll
    path("employee/pay/", views.Pay.as_view(), name="payroll")

]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static  # this is needed for file and image upload
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls', namespace='apps')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/templates/hrms/footer.html
<footer class="footer">
    <div class="container-fluid clearfix">
{#            <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © 2022#}
{#              <a href="#" target="_blank">Iron and Steel</a>. All rights reserved.</span>#}
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Project By Baxromov Shahzodbek
            </i>
            </span>
    </div>
</footer>

apps/templates/hrms/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title  %}{% endblock title %}</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'hrms/vendors/iconfonts/mdi/css/materialdesignicons.min.css' %} ">
  <link rel="stylesheet" href="{% static 'hrms/vendors/iconfonts/font-awesome/css/font-awesome.css' %} ">
 
  
  <link rel="stylesheet" href="{% static 'hrms/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'hrms/css/toastr.min.css' %}">
  <link rel="shortcut icon" href="{% static 'hrms/images/favicon.png' %}" />
</head>
  
<body>
  <div class="container-scroller">
    {% include "hrms/nav.html" %}
    <div class="container-fluid page-body-wrapper">
      {% include 'hrms/sidebar.html' %}
        {% block content %} {% endblock content %}
        {% include 'hrms/footer.html' %}
    </div>
  </div>
  <!-- plugins:js -->
  
  <script src="{% static 'hrms/vendors/js/vendor.bundle.base.js' %}"></script>
  <script src="{% static 'hrms/vendors/js/vendor.bundle.addons.js' %}"></script>
  <script src="{% static 'hrms/js/toastr.min.js' %}"></script>
  <script src="{% static 'hrms/js/sweetalert2@8.js' %}"></script>
  <script src="{% static 'hrms/js/pay.js' %}"></script>


  {% block noty %}
  {% endblock noty %}
</body>

</html>

apps/templates/hrms/nav.html
{% load static %}
<nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row">

    <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">
        <p class="display-4 mt-3 text-success">HRIS</p>
        <a class="navbar-brand brand-logo-mini" href="{% url 'apps:dashboard' %}">

            <img src="{{ user.thumb.url }}"/>
        </a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center">

        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item dropdown d-none d-xl-inline-block">

                <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown"
                   aria-expanded="false">
                    <span class="profile-text">{{ user.username | upper }}</span>
                    <img class="img-xs rounded-circle" src=" {{ user.thumb.url }} " alt="Profile image">
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
                    <a class="dropdown-item" href='{% url 'apps:logout' %}'>
                        Выйти
                    </a>
                </div>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
                data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
        </button>
    </div>
</nav>

apps/templates/hrms/sidebar.html
<nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
          <li class="nav-item nav-profile">
            <div class="nav-link">
              <div class="user-wrapper">
                <div class="profile-image">
                  <img src="{{user.thumb.url}}">
                </div>
                <div class="text-wrapper">
                  <p class="profile-name">{{user.username | upper}} </p>
                  <div>
                    <small class="designation text-muted">Администратор</small>
                    <span class="status-indicator online"></span>
                  </div>
                </div>
              </div>
              <a href="{% url 'apps:employee_new' %}" class="btn btn-success btn-block">Новые сотрудники
                <i class="mdi mdi-plus"></i>
              </a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'apps:dashboard' %}">
              <i class="fa  fa-dashboard"></i>
              <span class="menu-title">&emsp;Панель приборов</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'apps:employee_all' %}" aria-expanded="false" aria-controls="ui-basic">
              <i class="fa fa-list text-dark"></i>
              <span class="menu-title">&emsp;Работник</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'apps:attendance_new' %}">
              <i class="fa fa-calendar"></i>
              <span class="menu-title">&emsp;Посещаемость</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'apps:leave_new' %}">
              <i class="fa fa-sign-out "></i>
              <span class="menu-title">&emsp;Покинуть</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
              <i class="fa fa-folder "></i>
              <span class="menu-title">&emsp;Отделение</span>
              <i class="menu-arrow"></i>
            </a>
              <a class="nav-link" href="{% url 'apps:dept_new' %}"><i class="fa fa-plus"></i>&emsp;Новый отдел</a>
              
            <hr>

            <div class="collapse" id="ui-basic">
              <ul class="nav flex-column sub-menu">
              {% for dept in depts  %}
                <li class="nav-item">
                  <a class="nav-link" href="{{dept.get_absolute_url}}">{{dept.name}}</a>
                </li>
              {% endfor %}
              </ul>
            </div>
          </li>


          <li class="nav-item">
            <a class="nav-link" href="{% url 'apps:recruitmentall' %}">
              <i class="fa fa-database"></i>
              <span class="menu-title">&emsp;Прием на работу</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'apps:payroll' %}">
              <i class="fa fa-usd"></i>
              <span class="menu-title">&emsp;Платежная ведомость</span>
            </a>
          </li>

          {% comment %} <li class="nav-item">

          <li class="nav-item">
            <a class="nav-link" href="pages/icons/font-awesome.html">
              <i class="fa  fa-gears"></i>
              <span class="menu-title">&emsp;Настройки</span>
            </a>
          </li> {% endcomment %}
        </ul>
      </nav>